// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HotwireChatController from "./hotwire_chat_controller"
application.register("hotwire_chat", HotwireChatController)
